---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "qrcode"
    version: "0.0.1-SNAPSHOT"
    group: "mouad"
  name: "qrcode-service"
spec:
  ports:
  - name: "http"
    port: 8083
    targetPort: 8083
  selector:
    app: "qrcode"
    version: "0.0.1-SNAPSHOT"
    group: "mouad"
  type: "NodePort"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "qrcode"
    version: "0.0.1-SNAPSHOT"
    group: "mouad"
  name: "qrcode-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "qrcode"
      version: "0.0.1-SNAPSHOT"
      group: "mouad"
  template:
    metadata:
      labels:
        app: "qrcode"
        version: "0.0.1-SNAPSHOT"
        group: "mouad"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "0mounach0/qrcode"
        imagePullPolicy: "IfNotPresent"
        name: "qrcode-service"
        ports:
        - containerPort: 8083
          name: "http"
          protocol: "TCP"
