server:
  port: 8082
spring:
  application:
    name: movie-service
  cloud:
    kubernetes:
      enabled: true
    discovery:
      all-namespaces: true
api:
  key: a6967dfebc336586896d857fe4984a8c
dekorate:
  kubernetes:
    serviceType: "NodePort"