server:
  port: 8083
eureka:
  client:
    enabled: true
spring:
  application:
    name: qrcode-service
  cloud:
    kubernetes:
      enabled: false
    discovery:
      all-namespaces: true
dekorate:
  kubernetes:
    serviceType: "NodePort"