server:
  port: 8083
spring:
  application:
    name: qrcode-service
  cloud:
    kubernetes:
      enabled: true
    discovery:
      all-namespaces: true
dekorate:
  kubernetes:
    serviceType: "NodePort"